CREATE TABLE IF NOT EXISTS Record(
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    isWin BOOLEAN NOT NULL,
    roleType ENUM("TARGET", "GUARD", "HITMAN", "PSYCHOPATH") NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
);