DROP TABLE IF EXISTS SpawnLocation;
CREATE TABLE IF NOT EXISTS SpawnLocation (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    mapId INT NOT NULL, -- 1로 고정
    x FLOAT NOT NULL,
    y FLOAT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);